### ISSUE TITLE
[Doc / Other] Project Startup

### ISSUE THREAD

**Issue by andrewvallejo** [andrewvallejo/overlook#1]
# Project Startup

To ensure thoroughness of the project board itself, it must fulfill each item in the checklist 

## Checklist

- [x] #2 Project Board Setup 
- [x] #3 Directory Setup
- [x] #5 Make Class Issues checklist and skeleton
- [x] #6 Make Test Issues checklist and skeleton
- [x] #7 README.me 

## Further comments

Don't begin on working on any of the iterations until the set up is complete.
